import os
from dotenv import load_dotenv

load_dotenv()

# Telegram Bot
TOKEN = os.getenv("TOKEN")
SELF_URL = os.getenv("SELF_URL")  # https://your-service.onrender.com
PORT = int(os.getenv("PORT", 8000))

# CSV URLs
def get_env(name): return os.getenv(name)
ZONES_CSV_URL = get_env("ZONES_CSV_URL")
# UG
YUGO_ZAPAD_URL_UG, YUGO_ZAPAD_URL_UG_SP = get_env("YUGO_ZAPAD_URL_UG"), get_env("YUGO_ZAPAD_URL_UG_SP")
CENTRAL_URL_UG, CENTRAL_URL_UG_SP = get_env("CENTRAL_URL_UG"), get_env("CENTRAL_URL_UG_SP")
ZAPAD_URL_UG, ZAPAD_URL_UG_SP = get_env("ZAPAD_URL_UG"), get_env("ZAPAD_URL_UG_SP")
VOSTOCH_URL_UG, VOSTOCH_URL_UG_SP = get_env("VOSTOCH_URL_UG"), get_env("VOSTOCH_URL_UG_SP")
YUZH_URL_UG, YUZH_URL_UG_SP = get_env("YUZH_URL_UG"), get_env("YUZH_URL_UG_SP")
SEVERO_VOSTOCH_URL_UG, SEVERO_VOSTOCH_URL_UG_SP = get_env("SEVERO_VOSTOCH_URL_UG"), get_env("SEVERO_VOSTOCH_URL_UG_SP")
YUGO_VOSTOCH_URL_UG, YUGO_VOSTOCH_URL_UG_SP = get_env("YUGO_VOSTOCH_URL_UG"), get_env("YUGO_VOSTOCH_URL_UG_SP")
SEVER_URL_UG, SEVER_URL_UG_SP = get_env("SEVER_URL_UG"), get_env("SEVER_URL_UG_SP")
# RK
yugo_zapad_rk, yugo_zapad_rk_sp = get_env("YUGO_ZAPAD_URL_RK"), get_env("YUGO_ZAPAD_URL_RK_SP")
UST_LABINSK_URL_RK, UST_LABINSK_URL_RK_SP = get_env("UST_LABINSK_URL_RK"), get_env("UST_LABINSK_URL_RK_SP")
TIMASHEVSK_URL_RK, TIMASHEVSK_URL_RK_SP = get_env("TIMASHEVSK_URL_RK"), get_env("TIMASHEVSK_URL_RK_SP")
TIKHORETSK_URL_RK, TIKHORETSK_URL_RK_SP = get_env("TIKHORETSK_URL_RK"), get_env("TIKHORETSK_URL_RK_SP")
SOCHI_URL_RK, SOCHI_URL_RK_SP = get_env("SOCHI_URL_RK"), get_env("SOCHI_URL_RK_SP")
SLAVYANSK_URL_RK, SLAVYANSK_URL_RK_SP = get_env("SLAVYANSK_URL_RK"), get_env("SLAVYANSK_URL_RK_SP")
LENINGRADSK_URL_RK, LENINGRADSK_URL_RK_SP = get_env("LENINGRADSK_URL_RK"), get_env("LENINGRADSK_URL_RK_SP")
LABINSK_URL_RK, LABINSK_URL_RK_SP = get_env("LABINSK_URL_RK"), get_env("LABINSK_URL_RK_SP")
KRASNODAR_URL_RK, KRASNODAR_URL_RK_SP = get_env("KRASNODAR_URL_RK"), get_env("KRASNODAR_URL_RK_SP")
ARMAVIR_URL_RK, ARMAVIR_URL_RK_SP = get_env("ARMAVIR_URL_RK"), get_env("ARMAVIR_URL_RK_SP")
ADYGEYSK_URL_RK, ADYGEYSK_URL_RK_SP = get_env("ADYGEYSK_URL_RK"), get_env("ADYGEYSK_URL_RK_SP")
# Logs
NOTIFY_LOG_FILE_UG = os.getenv("NOTIFY_LOG_FILE_UG", "notify_log_ug.csv")
NOTIFY_LOG_FILE_RK = os.getenv("NOTIFY_LOG_FILE_RK", "notify_log_rk.csv")
